import Fastify, { FastifyRequest } from 'fastify';
import cookie from '@fastify/cookie';
import jwt from '@fastify/jwt';
import rateLimit from '@fastify/rate-limit';
import websocket from '@fastify/websocket';
import argon2 from 'argon2';
import { z, ZodError } from 'zod';
import { mkdirSync, createReadStream, createWriteStream, existsSync, rmSync, statfsSync } from 'node:fs';
import { open, rename, stat } from 'node:fs/promises';
import { join } from 'node:path';
import { pipeline } from 'node:stream/promises';
import { createHash, createHmac } from 'node:crypto';
import type { WebSocket } from 'ws';
import { loadConfig, type Config } from './config.js';
import { openDatabase, type Db } from './db.js';
import { AppError, future, id, now, sha256, token } from './util.js';

const credentials=z.object({email:z.string().email().max(254),password:z.string().min(10).max(200),displayName:z.string().min(1).max(80)});
const messageBody=z.object({kind:z.enum(['text','system','file','sticker','gif','poll']).default('text'),text:z.string().max(10000).optional(),fileId:z.string().uuid().optional(),replyToId:z.string().uuid().optional(),forwardedFromId:z.string().uuid().optional(),assetRef:z.string().regex(/^asset:[a-z0-9][a-z0-9/_-]{0,190}$/i).optional(),externalUrl:z.string().url().max(2048).optional()}).refine(v=>v.text||v.fileId||v.assetRef||v.externalUrl||v.kind==='poll',{message:'message content required'}).superRefine((v,ctx)=>{if(['sticker','gif'].includes(v.kind)&&!v.assetRef&&!v.externalUrl)ctx.addIssue({code:'custom',message:'Sticker/GIF needs assetRef or externalUrl'});if(v.externalUrl){const u=new URL(v.externalUrl);if(u.protocol!=='https:'||!['media.giphy.com','i.giphy.com','cdn.krug.local'].includes(u.hostname))ctx.addIssue({code:'custom',message:'External media URL is not allowlisted'})}});
const clean=(u:any,viewer?:any)=>{const contact=viewer&&viewer!==u.id;const visible=(value:string)=>value==='everyone'||(value==='contacts'&&contact);return {id:u.id,email:u.email,displayName:u.display_name,avatarUrl:visible(u.privacy_avatar??'everyone')?u.avatar_url:null,bio:visible(u.privacy_status??'contacts')?u.bio:null,role:u.role,lastSeenAt:visible(u.privacy_last_seen??'contacts')?u.last_seen_at:null,createdAt:u.created_at,privacy:viewer===u.id?{online:u.privacy_online,lastSeen:u.privacy_last_seen,avatar:u.privacy_avatar,status:u.privacy_status,readReceipts:!!u.privacy_read_receipts}:undefined};};
const mentionTokens=(text:string)=>[...text.matchAll(/(^|[^\w])@([\p{L}\p{N}_-]{1,80})/gu)].map(x=>x[2].toLowerCase());

export async function buildApp(options:{config?:Partial<Config>,db?:Db}={}){
 const config=loadConfig(options.config as any); const db=options.db??openDatabase(config.DATABASE_PATH); mkdirSync(config.STORAGE_PATH,{recursive:true});
 const app=Fastify({logger:config.NODE_ENV!=='test',bodyLimit:config.UPLOAD_CHUNK_BYTES+1024});
 await app.register(cookie); await app.register(jwt,{secret:config.JWT_SECRET}); await app.register(rateLimit,{max:120,timeWindow:'1 minute'}); await app.register(websocket);
 app.decorate('db',db);
 app.setErrorHandler((e,_,reply)=>{if(e instanceof AppError)return reply.code(e.statusCode).send({error:e.code,message:e.message});if(e instanceof ZodError)return reply.code(400).send({error:'VALIDATION_ERROR',details:e.issues});app.log.error(e);return reply.code((e as any).statusCode??500).send({error:'INTERNAL_ERROR',message:(e as any).statusCode?(e as any).message:'Internal server error'});});
 const auth=async(req:FastifyRequest)=>{await req.jwtVerify();if(req.user.type!=='access')throw new AppError(401,'UNAUTHORIZED','Access token required');};
 const member=(chatId:string,userId:string)=>{const row=db.prepare('SELECT * FROM chat_members WHERE chat_id=? AND user_id=? AND left_at IS NULL').get(chatId,userId) as any;if(!row)throw new AppError(403,'NOT_CHAT_MEMBER','Chat membership required');return row};
 const issue=(user:any)=>{const accessToken=app.jwt.sign({sub:user.id,role:user.role,type:'access'},{expiresIn:config.ACCESS_TTL});const raw=token(),rid=id();db.prepare('INSERT INTO refresh_tokens(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').run(rid,user.id,sha256(raw),future(config.REFRESH_TTL_DAYS));return {accessToken,refreshToken:`${rid}.${raw}`}};
 const setRefresh=(reply:any,value:string)=>reply.setCookie('krug_refresh',value,{httpOnly:true,secure:config.COOKIE_SECURE,sameSite:'strict',path:'/api/auth',maxAge:config.REFRESH_TTL_DAYS*86400});
 const sockets=new Map<string,Set<WebSocket>>(); const broadcast=(users:string[],event:any)=>{const data=JSON.stringify(event);for(const uid of users)for(const ws of sockets.get(uid)??[])if(ws.readyState===1)ws.send(data)}; const chatUsers=(cid:string)=>(db.prepare('SELECT user_id FROM chat_members WHERE chat_id=? AND left_at IS NULL').all(cid) as any[]).map(x=>x.user_id);
 const blocked=(a:string,b:string)=>!!db.prepare('SELECT 1 FROM user_blocks WHERE (blocker_id=? AND blocked_id=?) OR (blocker_id=? AND blocked_id=?)').get(a,b,b,a);
 const assertNotBlocked=(actor:string,users:string[])=>{if(users.some(userId=>userId!==actor&&blocked(actor,userId)))throw new AppError(403,'BLOCKED','This action is unavailable because a participant is blocked');};
 const graceCutoff=()=>new Date(Date.now()-config.CALL_RECONNECT_GRACE_SECONDS*1000).toISOString();
 const callUsers=(callId:string)=>((db.prepare('SELECT user_id FROM call_participants WHERE call_id=? AND (left_at IS NULL OR left_at>?)').all(callId,graceCutoff()) as any[]).map(x=>x.user_id));
 const assertCallAvailable=(userId:string,callId?:string)=>{const row=db.prepare("SELECT cp.call_id FROM call_participants cp JOIN calls c ON c.id=cp.call_id WHERE (cp.left_at IS NULL OR cp.left_at>?) AND c.status IN ('ringing','active') AND (? IS NULL OR cp.call_id<>?) LIMIT 1").get(graceCutoff(),callId??null,callId??null) as any;if(row)throw new AppError(409,'CALL_BUSY','User is already in another active call');};

 app.get('/health',async()=>({status:'ok'}));
 app.post('/api/auth/bootstrap',{config:{rateLimit:{max:5,timeWindow:'1 hour'}}},async(req,reply)=>{const b=credentials.parse(req.body);if((db.prepare('SELECT count(*) n FROM users').get() as any).n)throw new AppError(409,'ALREADY_INITIALIZED','Owner already exists');const uid=id();db.prepare("INSERT INTO users(id,email,password_hash,display_name,role) VALUES(?,?,?,?, 'owner')").run(uid,b.email,await argon2.hash(b.password),b.displayName);const u=db.prepare('SELECT * FROM users WHERE id=?').get(uid);const t=issue(u);setRefresh(reply,t.refreshToken);return reply.code(201).send({user:clean(u),accessToken:t.accessToken});});
 app.post('/api/auth/register',{config:{rateLimit:{max:10,timeWindow:'1 hour'}}},async(req,reply)=>{const b=credentials.extend({inviteToken:z.string().min(20)}).parse(req.body);const inv=db.prepare('SELECT * FROM invites WHERE token_hash=? AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP').get(sha256(b.inviteToken)) as any;if(!inv)throw new AppError(400,'INVALID_INVITE','Invite is invalid or expired');if((db.prepare("SELECT count(*) n FROM users WHERE status='active'").get() as any).n>=config.MAX_USERS)throw new AppError(409,'USER_LIMIT','User limit reached');const uid=id();const tx=db.transaction(()=>{db.prepare('INSERT INTO users(id,email,password_hash,display_name,role) VALUES(?,?,?,?,?)').run(uid,b.email,awaitHash,b.displayName,inv.role);db.prepare('UPDATE invites SET used_by=?,used_at=? WHERE id=?').run(uid,now(),inv.id)});const awaitHash=await argon2.hash(b.password);tx();const u=db.prepare('SELECT * FROM users WHERE id=?').get(uid);const t=issue(u);setRefresh(reply,t.refreshToken);return reply.code(201).send({user:clean(u),accessToken:t.accessToken});});
 app.post('/api/auth/login',{config:{rateLimit:{max:10,timeWindow:'15 minutes'}}},async(req,reply)=>{const b=z.object({email:z.string().email(),password:z.string()}).parse(req.body);const u=db.prepare("SELECT * FROM users WHERE email=? AND status='active'").get(b.email) as any;if(!u||!await argon2.verify(u.password_hash,b.password))throw new AppError(401,'INVALID_CREDENTIALS','Invalid email or password');const t=issue(u);setRefresh(reply,t.refreshToken);return {user:clean(u),accessToken:t.accessToken};});
 app.post('/api/auth/refresh',async(req,reply)=>{const value=(req.cookies as any).krug_refresh??(req.body as any)?.refreshToken;const [rid,raw]=String(value??'').split('.');const old=db.prepare('SELECT * FROM refresh_tokens WHERE id=? AND revoked_at IS NULL AND expires_at>CURRENT_TIMESTAMP').get(rid) as any;if(!old||!raw||old.token_hash!==sha256(raw))throw new AppError(401,'INVALID_REFRESH','Refresh token invalid');db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE id=?').run(now(),rid);const u=db.prepare("SELECT * FROM users WHERE id=? AND status='active'").get(old.user_id);const t=issue(u);setRefresh(reply,t.refreshToken);return {accessToken:t.accessToken};});
 app.post('/api/auth/logout',async(req,reply)=>{const [rid]=String((req.cookies as any).krug_refresh??'').split('.');if(rid)db.prepare('UPDATE refresh_tokens SET revoked_at=? WHERE id=?').run(now(),rid);reply.clearCookie('krug_refresh',{path:'/api/auth'});return reply.code(204).send();});
 app.post('/api/invites',{preHandler:auth},async(req,reply)=>{if(!['owner','admin'].includes(req.user.role))throw new AppError(403,'FORBIDDEN','Admin role required');const b=z.object({role:z.enum(['admin','member']).default('member'),expiresInHours:z.number().int().min(1).max(720).default(72)}).parse(req.body);if(req.user.role==='admin'&&b.role==='admin')throw new AppError(403,'FORBIDDEN','Only owner can invite admins');const raw=token();db.prepare('INSERT INTO invites(id,token_hash,role,created_by,expires_at) VALUES(?,?,?,?,?)').run(id(),sha256(raw),b.role,req.user.sub,new Date(Date.now()+b.expiresInHours*3600000).toISOString());return reply.code(201).send({inviteToken:raw,role:b.role});});

 app.get('/api/me',{preHandler:auth},async req=>clean(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.sub)));
 app.patch('/api/me',{preHandler:auth},async req=>{const b=z.object({displayName:z.string().min(1).max(80).optional(),avatarUrl:z.string().url().nullable().optional(),bio:z.string().max(500).nullable().optional()}).parse(req.body);db.prepare('UPDATE users SET display_name=COALESCE(?,display_name),avatar_url=?,bio=?,updated_at=? WHERE id=?').run(b.displayName??null,b.avatarUrl===undefined?(db.prepare('SELECT avatar_url FROM users WHERE id=?').get(req.user.sub) as any).avatar_url:b.avatarUrl,b.bio===undefined?(db.prepare('SELECT bio FROM users WHERE id=?').get(req.user.sub) as any).bio:b.bio,now(),req.user.sub);return clean(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.sub));});
 app.get('/api/users',{preHandler:auth},async req=>{const q=z.object({q:z.string().max(80).default('')}).parse(req.query);return (db.prepare("SELECT * FROM users WHERE status='active' AND (display_name LIKE ? OR email LIKE ?) ORDER BY display_name LIMIT 50").all(`%${q.q}%`,`%${q.q}%`) as any[]).map(clean)});

 app.post('/api/chats/direct',{preHandler:auth},async(req,reply)=>{const {userId}=z.object({userId:z.string().uuid()}).parse(req.body);if(userId===req.user.sub)throw new AppError(400,'INVALID_PARTICIPANT','Cannot chat with yourself');if(!db.prepare("SELECT 1 FROM users WHERE id=? AND status='active'").get(userId))throw new AppError(404,'USER_NOT_FOUND','User not found');const key=[req.user.sub,userId].sort().join(':');let c=db.prepare('SELECT * FROM chats WHERE direct_key=?').get(key) as any;if(!c){const cid=id();db.transaction(()=>{db.prepare("INSERT INTO chats(id,type,created_by,direct_key) VALUES(?, 'direct',?,?)").run(cid,req.user.sub,key);db.prepare("INSERT INTO chat_members(chat_id,user_id,member_role) VALUES(?,?, 'member'),(?,?, 'member')").run(cid,req.user.sub,cid,userId)})();c=db.prepare('SELECT * FROM chats WHERE id=?').get(cid)}return reply.code(201).send(c)});
 app.post('/api/chats/group',{preHandler:auth},async(req,reply)=>{const b=z.object({title:z.string().min(1).max(120),memberIds:z.array(z.string().uuid()).max(59).default([])}).parse(req.body);const ids=[...new Set([req.user.sub,...b.memberIds])];const cid=id();db.transaction(()=>{db.prepare("INSERT INTO chats(id,type,title,created_by) VALUES(?,'group',?,?)").run(cid,b.title,req.user.sub);const s=db.prepare('INSERT INTO chat_members(chat_id,user_id,member_role) VALUES(?,?,?)');for(const uid of ids)s.run(cid,uid,uid===req.user.sub?'owner':'member')})();return reply.code(201).send(db.prepare('SELECT * FROM chats WHERE id=?').get(cid))});
 app.get('/api/chats',{preHandler:auth},async req=>db.prepare('SELECT c.*,cm.archived_at,cm.pinned_at FROM chats c JOIN chat_members cm ON cm.chat_id=c.id WHERE cm.user_id=? AND cm.left_at IS NULL ORDER BY cm.pinned_at IS NULL,cm.pinned_at DESC,c.updated_at DESC').all(req.user.sub));
 app.post('/api/chats/:id/members',{preHandler:auth},async req=>{const cid=(req.params as any).id;const me=member(cid,req.user.sub);if(!['owner','admin'].includes(me.member_role))throw new AppError(403,'FORBIDDEN','Chat admin required');const b=z.object({userId:z.string().uuid(),role:z.enum(['admin','member']).default('member')}).parse(req.body);db.prepare('INSERT INTO chat_members(chat_id,user_id,member_role,left_at) VALUES(?,?,?,NULL) ON CONFLICT(chat_id,user_id) DO UPDATE SET member_role=excluded.member_role,left_at=NULL').run(cid,b.userId,b.role);broadcast(chatUsers(cid),{type:'chat.member_added',chatId:cid,userId:b.userId});return {ok:true}});
 app.delete('/api/chats/:id/members/:uid',{preHandler:auth},async req=>{const {id:cid,uid} = req.params as any;const me=member(cid,req.user.sub);if(uid!==req.user.sub&&!['owner','admin'].includes(me.member_role))throw new AppError(403,'FORBIDDEN','Chat admin required');db.prepare('UPDATE chat_members SET left_at=? WHERE chat_id=? AND user_id=?').run(now(),cid,uid);broadcast(chatUsers(cid),{type:'chat.member_removed',chatId:cid,userId:uid});return {ok:true}});
 app.patch('/api/chats/:id/preferences',{preHandler:auth},async req=>{const cid=(req.params as any).id;member(cid,req.user.sub);const b=z.object({archived:z.boolean().optional(),pinned:z.boolean().optional()}).parse(req.body);if(b.archived!==undefined)db.prepare('UPDATE chat_members SET archived_at=? WHERE chat_id=? AND user_id=?').run(b.archived?now():null,cid,req.user.sub);if(b.pinned!==undefined)db.prepare('UPDATE chat_members SET pinned_at=? WHERE chat_id=? AND user_id=?').run(b.pinned?now():null,cid,req.user.sub);return {ok:true}});

 app.post('/api/chats/:id/messages',{preHandler:auth,config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(req,reply)=>{const cid=(req.params as any).id;const me=member(cid,req.user.sub);const chat=db.prepare('SELECT * FROM chats WHERE id=?').get(cid) as any;if(chat.type==='direct')assertNotBlocked(req.user.sub,chatUsers(cid));if(chat.admins_only&&chat.type==='group'&&!['owner','admin'].includes(me.member_role))throw new AppError(403,'ADMINS_ONLY','Only group administrators can post');const b=messageBody.parse(req.body);if(b.fileId&&!db.prepare("SELECT 1 FROM uploads WHERE id=? AND status='ready'").get(b.fileId))throw new AppError(400,'FILE_NOT_READY','File is not ready');if(b.replyToId&&!db.prepare('SELECT 1 FROM messages WHERE id=? AND chat_id=?').get(b.replyToId,cid))throw new AppError(400,'INVALID_REPLY','Reply must reference a message in this chat');const mid=id();const expiresAt=chat.disappearing_seconds?new Date(Date.now()+chat.disappearing_seconds*1000).toISOString():null;const mentioned=mentionTokens(b.text??'');const members=db.prepare('SELECT u.id,u.display_name FROM chat_members cm JOIN users u ON u.id=cm.user_id WHERE cm.chat_id=? AND cm.left_at IS NULL').all(cid) as any[];const mentionRows=mentioned.map(token=>{const matches=members.filter(u=>u.display_name.toLowerCase()===token);if(matches.length!==1)throw new AppError(400,'INVALID_MENTION',`Unknown or ambiguous mention @${token}`);return {userId:matches[0].id,token}});db.transaction(()=>{db.prepare('INSERT INTO messages(id,chat_id,sender_id,kind,text,file_id,reply_to_id,forwarded_from_id,external_url,asset_ref,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(mid,cid,req.user.sub,b.kind,b.text??null,b.fileId??null,b.replyToId??null,b.forwardedFromId??null,b.externalUrl??null,b.assetRef??null,expiresAt);const insertMention=db.prepare('INSERT INTO message_mentions(message_id,user_id,token) VALUES(?,?,?)');for(const x of mentionRows)insertMention.run(mid,x.userId,x.token);db.prepare('UPDATE chats SET updated_at=? WHERE id=?').run(now(),cid)} )();const m=db.prepare('SELECT * FROM messages WHERE id=?').get(mid) as any;broadcast(chatUsers(cid),{type:'message.created',chatId:cid,message:{...m,mentions:mentionRows}});if(mentionRows.length)broadcast(mentionRows.map(x=>x.userId),{type:'message.mentioned',chatId:cid,messageId:mid,byUserId:req.user.sub});return reply.code(201).send({...m,mentions:mentionRows})});
 app.get('/api/chats/:id/messages',{preHandler:auth},async req=>{const cid=(req.params as any).id;member(cid,req.user.sub);const q=z.object({before:z.string().optional(),limit:z.coerce.number().int().min(1).max(100).default(50)}).parse(req.query);return db.prepare(`SELECT m.* FROM messages m WHERE m.chat_id=? AND m.created_at<? AND NOT EXISTS(SELECT 1 FROM message_deletions d WHERE d.message_id=m.id AND d.user_id=?) ORDER BY m.created_at DESC LIMIT ?`).all(cid,q.before??'9999-12-31',req.user.sub,q.limit)});
 app.post('/api/messages/:id/reactions',{preHandler:auth},async req=>{const mid=(req.params as any).id;const m=db.prepare('SELECT * FROM messages WHERE id=?').get(mid) as any;if(!m)throw new AppError(404,'MESSAGE_NOT_FOUND','Message not found');member(m.chat_id,req.user.sub);const {emoji}=z.object({emoji:z.string().min(1).max(16)}).parse(req.body);db.prepare('INSERT OR IGNORE INTO reactions(message_id,user_id,emoji) VALUES(?,?,?)').run(mid,req.user.sub,emoji);broadcast(chatUsers(m.chat_id),{type:'reaction.updated',messageId:mid,userId:req.user.sub,emoji,active:true});return {ok:true}});
 app.delete('/api/messages/:id/reactions/:emoji',{preHandler:auth},async req=>{const {id:mid,emoji}=req.params as any;const m=db.prepare('SELECT * FROM messages WHERE id=?').get(mid) as any;if(!m)throw new AppError(404,'MESSAGE_NOT_FOUND','Message not found');member(m.chat_id,req.user.sub);db.prepare('DELETE FROM reactions WHERE message_id=? AND user_id=? AND emoji=?').run(mid,req.user.sub,emoji);broadcast(chatUsers(m.chat_id),{type:'reaction.updated',messageId:mid,userId:req.user.sub,emoji,active:false});return {ok:true}});
 app.delete('/api/messages/:id',{preHandler:auth},async req=>{const mid=(req.params as any).id;const {scope}=z.object({scope:z.enum(['me','everyone'])}).parse(req.query);const m=db.prepare('SELECT * FROM messages WHERE id=?').get(mid) as any;if(!m)throw new AppError(404,'MESSAGE_NOT_FOUND','Message not found');member(m.chat_id,req.user.sub);if(scope==='everyone'){if(m.sender_id!==req.user.sub&&req.user.role!=='owner')throw new AppError(403,'FORBIDDEN','Only sender can delete for everyone');db.prepare("UPDATE messages SET text=NULL,file_id=NULL,deleted_for_everyone_at=? WHERE id=?").run(now(),mid);broadcast(chatUsers(m.chat_id),{type:'message.deleted',messageId:mid,scope:'everyone'});}else db.prepare('INSERT OR IGNORE INTO message_deletions(message_id,user_id) VALUES(?,?)').run(mid,req.user.sub);return {ok:true}});
 app.post('/api/messages/:id/receipt',{preHandler:auth},async req=>{const mid=(req.params as any).id;const m=db.prepare('SELECT * FROM messages WHERE id=?').get(mid) as any;if(!m)throw new AppError(404,'MESSAGE_NOT_FOUND','Message not found');member(m.chat_id,req.user.sub);const {state}=z.object({state:z.enum(['delivered','read'])}).parse(req.body);db.prepare(`INSERT INTO message_receipts(message_id,user_id,delivered_at,read_at) VALUES(?,?,?,?) ON CONFLICT(message_id,user_id) DO UPDATE SET delivered_at=COALESCE(message_receipts.delivered_at,excluded.delivered_at),read_at=COALESCE(message_receipts.read_at,excluded.read_at)`).run(mid,req.user.sub,now(),state==='read'?now():null);broadcast(chatUsers(m.chat_id),{type:`message.${state}`,messageId:mid,userId:req.user.sub});return {ok:true}});
 app.get('/api/search',{preHandler:auth},async req=>{const q=z.object({q:z.string().min(2).max(100),chatId:z.string().uuid().optional()}).parse(req.query);return db.prepare(`SELECT m.* FROM message_search s JOIN messages m ON m.id=s.message_id JOIN chat_members cm ON cm.chat_id=m.chat_id AND cm.user_id=? AND cm.left_at IS NULL WHERE message_search MATCH ? AND (? IS NULL OR m.chat_id=?) LIMIT 100`).all(req.user.sub,q.q,q.chatId??null,q.chatId??null)});

 app.post('/api/uploads',{preHandler:auth},async(req,reply)=>{const b=z.object({name:z.string().min(1).max(255),mimeType:z.string().min(1).max(120),sizeBytes:z.number().int().positive().max(config.MAX_FILE_BYTES),sha256:z.string().regex(/^[a-f0-9]{64}$/i)}).parse(req.body);const fs=statfsSync(config.STORAGE_PATH);if(fs.bavail*fs.bsize<config.MIN_FREE_BYTES)throw new AppError(507,'INSUFFICIENT_STORAGE','Not enough free disk space');const used=(db.prepare("SELECT COALESCE(sum(size_bytes),0) n FROM uploads WHERE status IN ('uploading','assembling','ready')").get() as any).n;if(used+b.sizeBytes>config.MAX_STORAGE_BYTES)throw new AppError(507,'STORAGE_QUOTA','Storage quota exceeded');const uid=id();mkdirSync(join(config.STORAGE_PATH,uid,'chunks'),{recursive:true});db.prepare("INSERT INTO uploads(id,owner_id,original_name,mime_type,size_bytes,chunk_size,expected_sha256,status,expires_at) VALUES(?,?,?,?,?,?,?,'uploading',?)").run(uid,req.user.sub,b.name,b.mimeType,b.sizeBytes,config.UPLOAD_CHUNK_BYTES,new Date(Date.now()+config.FILE_RETENTION_HOURS*3600000).toISOString());return reply.code(201).send({id:uid,chunkSize:config.UPLOAD_CHUNK_BYTES,totalChunks:Math.ceil(b.sizeBytes/config.UPLOAD_CHUNK_BYTES)})});
 app.get('/api/uploads/:id',{preHandler:auth},async req=>{const u=db.prepare('SELECT * FROM uploads WHERE id=?').get((req.params as any).id) as any;if(!u)throw new AppError(404,'UPLOAD_NOT_FOUND','Upload not found');const chunks=db.prepare('SELECT chunk_index,size_bytes,sha256 FROM upload_chunks WHERE upload_id=? ORDER BY chunk_index').all(u.id);return {...u,chunks}});
 app.put('/api/uploads/:id/chunks/:index',{preHandler:auth},async(req,reply)=>{const {id:uid,index}=req.params as any;const u=db.prepare("SELECT * FROM uploads WHERE id=? AND owner_id=? AND status='uploading'").get(uid,req.user.sub) as any;if(!u)throw new AppError(404,'UPLOAD_NOT_FOUND','Upload not found');const idx=Number(index),total=Math.ceil(u.size_bytes/u.chunk_size);if(!Number.isInteger(idx)||idx<0||idx>=total)throw new AppError(400,'INVALID_CHUNK','Invalid chunk index');const expected=idx===total-1?u.size_bytes-idx*u.chunk_size:u.chunk_size;const len=Number(req.headers['content-length']);if(len!==expected)throw new AppError(400,'INVALID_CHUNK_SIZE',`Expected ${expected} bytes`);const path=join(config.STORAGE_PATH,uid,'chunks',String(idx));const hash=createHash('sha256');let size=0;req.raw.on('data',c=>{size+=c.length;hash.update(c)});await pipeline(req.raw,createWriteStream(path,{flags:'w'}));if(size!==expected)throw new AppError(400,'INVALID_CHUNK_SIZE','Incomplete chunk');const digest=hash.digest('hex');db.prepare('INSERT INTO upload_chunks(upload_id,chunk_index,size_bytes,sha256,storage_path) VALUES(?,?,?,?,?) ON CONFLICT(upload_id,chunk_index) DO UPDATE SET size_bytes=excluded.size_bytes,sha256=excluded.sha256,storage_path=excluded.storage_path').run(uid,idx,size,digest,path);return reply.code(201).send({index:idx,sizeBytes:size,sha256:digest})});
 app.post('/api/uploads/:id/complete',{preHandler:auth},async req=>{const uid=(req.params as any).id;const u=db.prepare("SELECT * FROM uploads WHERE id=? AND owner_id=? AND status='uploading'").get(uid,req.user.sub) as any;if(!u)throw new AppError(404,'UPLOAD_NOT_FOUND','Upload not found');const chunks=db.prepare('SELECT * FROM upload_chunks WHERE upload_id=? ORDER BY chunk_index').all(uid) as any[],total=Math.ceil(u.size_bytes/u.chunk_size);if(chunks.length!==total)throw new AppError(409,'MISSING_CHUNKS','Upload has missing chunks');db.prepare("UPDATE uploads SET status='assembling' WHERE id=?").run(uid);const finalPath=join(config.STORAGE_PATH,uid,'file.tmp');const out=createWriteStream(finalPath);const hash=createHash('sha256');for(const c of chunks){const input=createReadStream(c.storage_path);input.on('data',x=>hash.update(x));await pipeline(input,out,{end:false});}out.end();await new Promise<void>((r,j)=>{out.on('finish',r);out.on('error',j)});const digest=hash.digest('hex');if(digest!==u.expected_sha256){db.prepare("UPDATE uploads SET status='failed',actual_sha256=? WHERE id=?").run(digest,uid);throw new AppError(422,'CHECKSUM_MISMATCH','File checksum mismatch')}const ready=join(config.STORAGE_PATH,uid,'file');await rename(finalPath,ready);db.prepare("UPDATE uploads SET status='ready',actual_sha256=?,storage_path=?,completed_at=? WHERE id=?").run(digest,ready,now(),uid);rmSync(join(config.STORAGE_PATH,uid,'chunks'),{recursive:true,force:true});return {id:uid,status:'ready',sha256:digest}});
 app.get('/api/files/:id',{preHandler:auth},async(req,reply)=>{const u=db.prepare("SELECT * FROM uploads WHERE id=? AND status='ready' AND expires_at>CURRENT_TIMESTAMP").get((req.params as any).id) as any;if(!u||!u.storage_path||!existsSync(u.storage_path))throw new AppError(404,'FILE_NOT_FOUND','File not found or expired');reply.header('content-type',u.mime_type).header('content-length',u.size_bytes).header('content-disposition',`attachment; filename*=UTF-8''${encodeURIComponent(u.original_name)}`);return reply.send(createReadStream(u.storage_path))});
 app.post('/api/files/:id/download-confirmation',{preHandler:auth},async req=>{const uid=(req.params as any).id;if(!db.prepare("SELECT 1 FROM uploads WHERE id=? AND status='ready'").get(uid))throw new AppError(404,'FILE_NOT_FOUND','File not found');db.prepare('INSERT OR REPLACE INTO download_confirmations(upload_id,user_id,confirmed_at) VALUES(?,?,?)').run(uid,req.user.sub,now());return {ok:true}});

 app.post('/api/chats/:id/calls',{preHandler:auth},async(req,reply)=>{const cid=(req.params as any).id;member(cid,req.user.sub);const users=chatUsers(cid);assertNotBlocked(req.user.sub,users);assertCallAvailable(req.user.sub);if(db.prepare("SELECT 1 FROM calls WHERE chat_id=? AND status IN ('ringing','active')").get(cid))throw new AppError(409,'CALL_ACTIVE','A call is already active');const call=id();db.transaction(()=>{db.prepare("INSERT INTO calls(id,chat_id,started_by,status) VALUES(?,?,?,'ringing')").run(call,cid,req.user.sub);db.prepare('INSERT INTO call_participants(call_id,user_id) VALUES(?,?)').run(call,req.user.sub)})();broadcast(users,{type:'call.ringing',callId:call,chatId:cid,from:req.user.sub});return reply.code(201).send({id:call})});
 app.post('/api/calls/:id/join',{preHandler:auth},async req=>{const call=db.prepare("SELECT * FROM calls WHERE id=? AND status IN ('ringing','active')").get((req.params as any).id) as any;if(!call)throw new AppError(404,'CALL_NOT_FOUND','Active call not found');member(call.chat_id,req.user.sub);const count=(db.prepare('SELECT count(*) n FROM call_participants WHERE call_id=? AND left_at IS NULL').get(call.id) as any).n;if(count>=3&&!db.prepare('SELECT 1 FROM call_participants WHERE call_id=? AND user_id=? AND left_at IS NULL').get(call.id,req.user.sub))throw new AppError(409,'CALL_FULL','Call participant limit is 3');db.prepare('INSERT INTO call_participants(call_id,user_id,left_at) VALUES(?,?,NULL) ON CONFLICT(call_id,user_id) DO UPDATE SET joined_at=CURRENT_TIMESTAMP,left_at=NULL').run(call.id,req.user.sub);db.prepare("UPDATE calls SET status='active' WHERE id=?").run(call.id);broadcast(chatUsers(call.chat_id),{type:'call.joined',callId:call.id,userId:req.user.sub});return {ok:true}});
 app.post('/api/calls/:id/leave',{preHandler:auth},async req=>{const call=db.prepare('SELECT * FROM calls WHERE id=?').get((req.params as any).id) as any;if(!call)throw new AppError(404,'CALL_NOT_FOUND','Call not found');db.prepare('UPDATE call_participants SET left_at=? WHERE call_id=? AND user_id=?').run(now(),call.id,req.user.sub);if(!(db.prepare('SELECT 1 FROM call_participants WHERE call_id=? AND left_at IS NULL').get(call.id)))db.prepare("UPDATE calls SET status='ended',ended_at=? WHERE id=?").run(now(),call.id);broadcast(chatUsers(call.chat_id),{type:'call.left',callId:call.id,userId:req.user.sub});return {ok:true}});
 // GET /api/calls/turn-config — time-limited TURN credentials (RFC 5389 HMAC-SHA1)
 app.get('/api/calls/turn-config', { preHandler: auth }, async (req) => {
  const secret = config.TURN_SHARED_SECRET;
  if (!secret) {
    return { iceServers: [{ urls: 'stun:stun.l.google.com:19302' }] };
  }
  const ttl = 86400;
  const timestamp = Math.floor(Date.now() / 1000) + ttl;
  const username = `${timestamp}:krug`;
  const credential = createHmac('sha1', secret).update(username).digest('base64');
  const host = config.TURN_HOST ?? (req as FastifyRequest).hostname.split(':')[0];
  return {
    iceServers: [
      { urls: 'stun:stun.l.google.com:19302' },
      {
        urls: [`turn:${host}:3478`, `turns:${host}:5349`],
        username,
        credential,
      },
    ],
    ttl,
  };
 });

 app.get('/ws',{websocket:true},(socket,req)=>{let uid:string|undefined;try{const query=z.object({token:z.string()}).parse(req.query);const p=app.jwt.verify<{sub:string;type:string}>(query.token);if(p.type!=='access')throw Error();uid=p.sub;const set=sockets.get(uid)??new Set();set.add(socket);sockets.set(uid,set);db.prepare('UPDATE users SET last_seen_at=? WHERE id=?').run(now(),uid);socket.send(JSON.stringify({type:'session.ready',userId:uid}));broadcast([...sockets.keys()],{type:'presence.online',userId:uid});socket.on('message',(raw: Buffer)=>{try{const m=z.object({type:z.enum(['typing.start','typing.stop','webrtc.offer','webrtc.answer','webrtc.ice']),chatId:z.string().uuid(),targetUserId:z.string().uuid().optional(),callId:z.string().uuid().optional(),payload:z.unknown().optional()}).parse(JSON.parse(raw.toString()));member(m.chatId,uid!);if(m.type.startsWith('webrtc.')){if(!m.callId||!m.targetUserId)throw Error('callId and targetUserId required');const c=db.prepare("SELECT 1 FROM call_participants a JOIN call_participants b ON b.call_id=a.call_id WHERE a.call_id=? AND a.user_id=? AND a.left_at IS NULL AND b.user_id=? AND b.left_at IS NULL").get(m.callId,uid,m.targetUserId);if(!c)throw Error('Not active call participants');broadcast([m.targetUserId],{...m,fromUserId:uid});}else broadcast(chatUsers(m.chatId).filter(x=>x!==uid),{type:m.type,chatId:m.chatId,userId:uid});}catch(e:any){socket.send(JSON.stringify({type:'error',code:'INVALID_EVENT',message:e.message}))}});socket.on('close',()=>{set.delete(socket);if(!set.size){sockets.delete(uid!);db.prepare('UPDATE users SET last_seen_at=? WHERE id=?').run(now(),uid);broadcast([...sockets.keys()],{type:'presence.offline',userId:uid,lastSeenAt:now()})}});}catch{socket.close(1008,'Unauthorized')}});

 const admin=(cid:string,uid:string)=>['owner','admin'].includes(member(cid,uid).member_role);
 app.patch('/api/me/privacy',{preHandler:auth},async req=>{const b=z.object({online:z.enum(['everyone','contacts','nobody']).optional(),lastSeen:z.enum(['everyone','contacts','nobody']).optional(),avatar:z.enum(['everyone','contacts','nobody']).optional(),status:z.enum(['everyone','contacts','nobody']).optional(),readReceipts:z.boolean().optional()}).parse(req.body);const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.sub) as any;db.prepare('UPDATE users SET privacy_online=?,privacy_last_seen=?,privacy_avatar=?,privacy_status=?,privacy_read_receipts=? WHERE id=?').run(b.online??u.privacy_online,b.lastSeen??u.privacy_last_seen,b.avatar??u.privacy_avatar,b.status??u.privacy_status,b.readReceipts===undefined?u.privacy_read_receipts:Number(b.readReceipts),req.user.sub);broadcast([...sockets.keys()],{type:'privacy.updated',userId:req.user.sub});return clean(db.prepare('SELECT * FROM users WHERE id=?').get(req.user.sub),req.user.sub)});
 app.post('/api/users/:id/block',{preHandler:auth},async req=>{const target=(req.params as any).id;if(target===req.user.sub)throw new AppError(400,'INVALID_BLOCK','Cannot block yourself');db.prepare('INSERT OR IGNORE INTO user_blocks(blocker_id,blocked_id) VALUES(?,?)').run(req.user.sub,target);broadcast([target],{type:'user.blocked',byUserId:req.user.sub});return {ok:true}});app.delete('/api/users/:id/block',{preHandler:auth},async req=>{db.prepare('DELETE FROM user_blocks WHERE blocker_id=? AND blocked_id=?').run(req.user.sub,(req.params as any).id);return {ok:true}});
 app.patch('/api/chats/:id/mute',{preHandler:auth},async req=>{const cid=(req.params as any).id;member(cid,req.user.sub);const b=z.object({mutedUntil:z.string().datetime().nullable().optional(),forever:z.boolean().default(false)}).parse(req.body);db.prepare('UPDATE chat_members SET muted_forever=?,muted_until=? WHERE chat_id=? AND user_id=?').run(Number(b.forever),b.forever?null:b.mutedUntil??null,cid,req.user.sub);return {ok:true}});
 app.patch('/api/chats/:id/disappearing',{preHandler:auth},async req=>{const cid=(req.params as any).id;if(!admin(cid,req.user.sub))throw new AppError(403,'FORBIDDEN','Chat admin required');const b=z.object({seconds:z.number().int().min(60).max(2592000).nullable()}).parse(req.body);db.prepare('UPDATE chats SET disappearing_seconds=? WHERE id=?').run(b.seconds,cid);broadcast(chatUsers(cid),{type:'chat.disappearing_updated',chatId:cid,seconds:b.seconds});return {ok:true}});
 app.patch('/api/messages/:id',{preHandler:auth},async req=>{const mid=(req.params as any).id,m=db.prepare('SELECT * FROM messages WHERE id=?').get((req.params as any).id) as any;if(!m)throw new AppError(404,'MESSAGE_NOT_FOUND','Message not found');if(m.sender_id!==req.user.sub||Date.now()-Date.parse(m.created_at)>900000)throw new AppError(403,'EDIT_FORBIDDEN','Author and edit window required');const b=z.object({text:z.string().min(1).max(10000)}).parse(req.body);db.prepare('UPDATE messages SET text=?,edited_at=?,edited_by=?,edit_count=edit_count+1 WHERE id=?').run(b.text,now(),req.user.sub,mid);broadcast(chatUsers(m.chat_id),{type:'message.edited',chatId:m.chat_id,messageId:mid});return db.prepare('SELECT * FROM messages WHERE id=?').get(mid)});
 app.post('/api/messages/:id/pin',{preHandler:auth},async req=>{const m=db.prepare('SELECT * FROM messages WHERE id=?').get((req.params as any).id) as any;if(!m)throw new AppError(404,'MESSAGE_NOT_FOUND','Message not found');if(!admin(m.chat_id,req.user.sub))throw new AppError(403,'FORBIDDEN','Chat admin required');db.prepare('INSERT OR IGNORE INTO message_pins(chat_id,message_id,pinned_by) VALUES(?,?,?)').run(m.chat_id,m.id,req.user.sub);broadcast(chatUsers(m.chat_id),{type:'message.pinned',chatId:m.chat_id,messageId:m.id});return {ok:true}});app.delete('/api/messages/:id/pin',{preHandler:auth},async req=>{const m=db.prepare('SELECT * FROM messages WHERE id=?').get((req.params as any).id) as any;if(!m||!admin(m.chat_id,req.user.sub))throw new AppError(403,'FORBIDDEN','Chat admin required');db.prepare('DELETE FROM message_pins WHERE message_id=?').run(m.id);broadcast(chatUsers(m.chat_id),{type:'message.unpinned',chatId:m.chat_id,messageId:m.id});return {ok:true}});
 app.post('/api/chats/:id/polls',{preHandler:auth},async(req,reply)=>{const cid=(req.params as any).id;member(cid,req.user.sub);const b=z.object({question:z.string().min(1).max(500),options:z.array(z.string().min(1).max(200)).min(2).max(20),multipleChoice:z.boolean().default(false)}).parse(req.body),mid=id(),pid=id();db.transaction(()=>{db.prepare("INSERT INTO messages(id,chat_id,sender_id,kind,text) VALUES(?,?,?,'poll',?)").run(mid,cid,req.user.sub,b.question);db.prepare('INSERT INTO polls(id,message_id,question,multiple_choice,created_by) VALUES(?,?,?,?,?)').run(pid,mid,b.question,Number(b.multipleChoice),req.user.sub);const q=db.prepare('INSERT INTO poll_options(id,poll_id,position,text) VALUES(?,?,?,?)');b.options.forEach((x,n)=>q.run(id(),pid,n,x))})();const poll={...(db.prepare('SELECT * FROM polls WHERE id=?').get(pid) as any),options:db.prepare('SELECT * FROM poll_options WHERE poll_id=?').all(pid)};broadcast(chatUsers(cid),{type:'poll.created',chatId:cid,poll});return reply.code(201).send(poll)});
 app.post('/api/polls/:id/votes',{preHandler:auth},async req=>{const p=db.prepare('SELECT p.*,m.chat_id FROM polls p JOIN messages m ON m.id=p.message_id WHERE p.id=?').get((req.params as any).id) as any;if(!p)throw new AppError(404,'POLL_NOT_FOUND','Poll not found');member(p.chat_id,req.user.sub);const b=z.object({optionIds:z.array(z.string().uuid()).min(1).max(20)}).parse(req.body);if(!p.multiple_choice&&b.optionIds.length!==1)throw new AppError(400,'SINGLE_CHOICE','Only one option allowed');db.transaction(()=>{if(!p.multiple_choice)db.prepare('DELETE FROM poll_votes WHERE poll_id=? AND user_id=?').run(p.id,req.user.sub);const q=db.prepare('INSERT OR IGNORE INTO poll_votes(poll_id,option_id,user_id) VALUES(?,?,?)');b.optionIds.forEach(x=>{if(!db.prepare('SELECT 1 FROM poll_options WHERE id=? AND poll_id=?').get(x,p.id))throw new AppError(400,'INVALID_OPTION','Option not in poll');q.run(p.id,x,req.user.sub)})})();const results=db.prepare('SELECT o.id,o.text,count(v.user_id) votes FROM poll_options o LEFT JOIN poll_votes v ON v.option_id=o.id WHERE o.poll_id=? GROUP BY o.id').all(p.id);broadcast(chatUsers(p.chat_id),{type:'poll.updated',chatId:p.chat_id,pollId:p.id,results});return {results}});
 app.get('/api/polls/:id/results',{preHandler:auth},async req=>db.prepare('SELECT o.id,o.text,count(v.user_id) votes FROM poll_options o LEFT JOIN poll_votes v ON v.option_id=o.id WHERE o.poll_id=? GROUP BY o.id').all((req.params as any).id));
 app.post('/api/admin/cleanup',{preHandler:auth},async req=>{if(req.user.role!=='owner')throw new AppError(403,'FORBIDDEN','Owner role required');const r=db.prepare("UPDATE messages SET text=NULL,file_id=NULL,external_url=NULL,asset_ref=NULL,expired_at=? WHERE expires_at<=CURRENT_TIMESTAMP AND expired_at IS NULL").run(now());return {expiredMessages:r.changes}});
 const cleanup=()=>{db.prepare("UPDATE messages SET text=NULL,file_id=NULL,external_url=NULL,asset_ref=NULL,expired_at=? WHERE expires_at<=CURRENT_TIMESTAMP AND expired_at IS NULL").run(now());const expired=db.prepare("SELECT id,storage_path FROM uploads WHERE expires_at<=CURRENT_TIMESTAMP AND status!='expired'").all() as any[];for(const u of expired){rmSync(join(config.STORAGE_PATH,u.id),{recursive:true,force:true});db.prepare("UPDATE uploads SET status='expired',storage_path=NULL WHERE id=?").run(u.id)}};const timer=setInterval(cleanup,3600000);timer.unref();app.addHook('onClose',async()=>{clearInterval(timer);if(!options.db)db.close()});
 return app;
}

declare module 'fastify' { interface FastifyInstance { db: Db } }
